# Dependencies
markdown:         redcarpet
pygments:         false

# Permalinks
permalink:        pretty

# Setup
title:            Student Union
tagline:          'A site for the Brandeis Student Union'
description:      'A website for the Brandeis Student Union. Has resources for the student body.'
url:              union.brandeis.edu

author:
  name:           'David Barsky'
  url:            https://twitter.com/thramp

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/thramp/union
